### ISSUE TITLE
[BUG] FATAL: Unsupported file type possibly due to  EBADENGINE Unsupported engine warning during Docker build

### ISSUE THREAD

**Issue by mprins** [tj-actions/renovate-config-validator#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

It seems the Dockerfile of v1.2 is using an unsupported Node version, causing failure of the validation

### To Reproduce

use 
```yaml
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Renovate Config Validator
        uses: tj-actions/renovate-config-validator@v1.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.80.1
        with:
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
```
in a private repository

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

no failure when vaildating

### Relevant log output

```shell
2022-02-14T13:12:34.9585094Z Requested labels: ubuntu-latest
2022-02-14T13:12:34.9585155Z Job defined at: mprins/containers/.github/workflows/renovate.yml@refs/heads/master
2022-02-14T13:12:34.9585184Z Waiting for a runner to pick up this job...
2022-02-14T13:12:35.7868125Z Job is waiting for a hosted runner to come online.
2022-02-14T13:12:41.6853770Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2022-02-14T13:12:45.7802816Z Current runner version: '2.287.1'
2022-02-14T13:12:45.7829919Z ##[group]Operating System
2022-02-14T13:12:45.7830469Z Ubuntu
2022-02-14T13:12:45.7830781Z 20.04.3
2022-02-14T13:12:45.7831012Z LTS
2022-02-14T13:12:45.7831318Z ##[endgroup]
2022-02-14T13:12:45.7831653Z ##[group]Virtual Environment
2022-02-14T13:12:45.7832046Z Environment: ubuntu-20.04
2022-02-14T13:12:45.7832384Z Version: 20220207.1
2022-02-14T13:12:45.7832866Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220207.1/images/linux/Ubuntu2004-Readme.md
2022-02-14T13:12:45.7833548Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220207.1
2022-02-14T13:12:45.7834044Z ##[endgroup]
2022-02-14T13:12:45.7834390Z ##[group]Virtual Environment Provisioner
2022-02-14T13:12:45.7834764Z 1.0.0.0-main-20220202-1
2022-02-14T13:12:45.7835077Z ##[endgroup]
2022-02-14T13:12:45.7836042Z ##[group]GITHUB_TOKEN Permissions
2022-02-14T13:12:45.7836672Z Actions: write
2022-02-14T13:12:45.7837128Z Checks: write
2022-02-14T13:12:45.7837450Z Contents: write
2022-02-14T13:12:45.7837829Z Deployments: write
2022-02-14T13:12:45.7838162Z Discussions: write
2022-02-14T13:12:45.7838436Z Issues: write
2022-02-14T13:12:45.7838742Z Metadata: read
2022-02-14T13:12:45.7839008Z Packages: write
2022-02-14T13:12:45.7839368Z Pages: write
2022-02-14T13:12:45.7839689Z PullRequests: write
2022-02-14T13:12:45.7839996Z RepositoryProjects: write
2022-02-14T13:12:45.7840350Z SecurityEvents: write
2022-02-14T13:12:45.7840722Z Statuses: write
2022-02-14T13:12:45.7840990Z ##[endgroup]
2022-02-14T13:12:45.7844634Z Secret source: Actions
2022-02-14T13:12:45.7845086Z Prepare workflow directory
2022-02-14T13:12:45.8668857Z Prepare all required actions
2022-02-14T13:12:45.8851020Z Getting action download info
2022-02-14T13:12:46.0681245Z Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)
2022-02-14T13:12:46.4040876Z Download action repository 'tj-actions/renovate-config-validator@v1.2' (SHA:37b201fec7e793b89ed3569eb033dbc76ba5e07c)
2022-02-14T13:12:46.6270413Z Download action repository 'renovatebot/github-action@v31.80.1' (SHA:788b1d3d96a822f54b9ac7c114bddf7623664e61)
2022-02-14T13:12:47.0846173Z ##[group]Build container for action use: '/home/runner/work/_actions/tj-actions/renovate-config-validator/v1.2/Dockerfile'.
2022-02-14T13:12:47.0917292Z ##[command]/usr/bin/docker build -t 7db2d7:5a66464a3dc148e184d99d9091fea3b7 -f "/home/runner/work/_actions/tj-actions/renovate-config-validator/v1.2/Dockerfile" "/home/runner/work/_actions/tj-actions/renovate-config-validator/v1.2"
2022-02-14T13:12:47.2273588Z Sending build context to Docker daemon  28.16kB
2022-02-14T13:12:47.2275054Z 
2022-02-14T13:12:47.2604297Z Step 1/7 : FROM node:15.14.0-alpine3.10
2022-02-14T13:12:47.5483756Z 15.14.0-alpine3.10: Pulling from library/node
2022-02-14T13:12:47.6216159Z 396c31837116: Pulling fs layer
2022-02-14T13:12:47.6216798Z af9b8684c400: Pulling fs layer
2022-02-14T13:12:47.6217052Z cbd1aa5ac970: Pulling fs layer
2022-02-14T13:12:47.6217341Z b3fa28fb3cc2: Pulling fs layer
2022-02-14T13:12:47.6217672Z b3fa28fb3cc2: Waiting
2022-02-14T13:12:47.7420465Z 396c31837116: Verifying Checksum
2022-02-14T13:12:47.7478701Z 396c31837116: Download complete
2022-02-14T13:12:47.7611687Z cbd1aa5ac970: Verifying Checksum
2022-02-14T13:12:47.7615062Z cbd1aa5ac970: Download complete
2022-02-14T13:12:47.8477596Z b3fa28fb3cc2: Verifying Checksum
2022-02-14T13:12:47.8481238Z b3fa28fb3cc2: Download complete
2022-02-14T13:12:47.9521930Z 396c31837116: Pull complete
2022-02-14T13:12:47.9851440Z af9b8684c400: Verifying Checksum
2022-02-14T13:12:47.9855403Z af9b8684c400: Download complete
2022-02-14T13:12:50.1112976Z af9b8684c400: Pull complete
2022-02-14T13:12:50.2430090Z cbd1aa5ac970: Pull complete
2022-02-14T13:12:50.3022356Z b3fa28fb3cc2: Pull complete
2022-02-14T13:12:50.3070125Z Digest: sha256:7289e0545da1c88aa84d98e77beead2ea1ba5a12c9cb28fd756955d917d69bcd
2022-02-14T13:12:50.3085627Z Status: Downloaded newer image for node:15.14.0-alpine3.10
2022-02-14T13:12:50.3101849Z  ---> fd1f8547e2ff
2022-02-14T13:12:50.3102207Z Step 2/7 : LABEL maintainer="Tonye Jack <jtonye@ymail.com>"
2022-02-14T13:12:50.3301150Z  ---> Running in dbd6efd5983d
2022-02-14T13:12:51.0154831Z Removing intermediate container dbd6efd5983d
2022-02-14T13:12:51.0155453Z  ---> da5d5a2810e9
2022-02-14T13:12:51.0155818Z Step 3/7 : RUN apk add bash
2022-02-14T13:12:51.0353898Z  ---> Running in c1ee7a4d27e7
2022-02-14T13:12:51.3147297Z fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
2022-02-14T13:12:51.4018570Z fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
2022-02-14T13:12:51.4932324Z (1/4) Installing ncurses-terminfo-base (6.1_p20190518-r2)
2022-02-14T13:12:51.5017869Z (2/4) Installing ncurses-libs (6.1_p20190518-r2)
2022-02-14T13:12:51.5134646Z (3/4) Installing readline (8.0.0-r0)
2022-02-14T13:12:51.5218657Z (4/4) Installing bash (5.0.0-r0)
2022-02-14T13:12:51.5384397Z Executing bash-5.0.0-r0.post-install
2022-02-14T13:12:51.5404070Z Executing busybox-1.30.1-r5.trigger
2022-02-14T13:12:51.5437165Z OK: 9 MiB in 20 packages
2022-02-14T13:12:52.0177808Z Removing intermediate container c1ee7a4d27e7
2022-02-14T13:12:52.0187109Z  ---> 9eb2ca360c13
2022-02-14T13:12:52.0187835Z Step 4/7 : RUN npm install -g npm@7.10.0
2022-02-14T13:12:52.0408046Z  ---> Running in 4501f2b0efd3
2022-02-14T13:12:54.9030001Z 
2022-02-14T13:12:54.9030846Z changed 14 packages, and audited 253 packages in 3s
2022-02-14T13:12:54.9031358Z 
2022-02-14T13:12:54.9031643Z 11 packages are looking for funding
2022-02-14T13:12:54.9031942Z   run `npm fund` for details
2022-02-14T13:12:54.9109164Z 
2022-02-14T13:12:54.9109646Z 9 vulnerabilities (8 moderate, 1 high)
2022-02-14T13:12:54.9144301Z 
2022-02-14T13:12:54.9152744Z To address issues that do not require attention, run:
2022-02-14T13:12:54.9153014Z   npm audit fix
2022-02-14T13:12:54.9153147Z 
2022-02-14T13:12:54.9153290Z To address all issues (including breaking changes), run:
2022-02-14T13:12:54.9153565Z   npm audit fix --force
2022-02-14T13:12:54.9153700Z 
2022-02-14T13:12:54.9153792Z Run `npm audit` for details.
2022-02-14T13:12:54.9154005Z [91mnpm notice 
2022-02-14T13:12:54.9154543Z npm notice New major version of npm available! 7.7.6 -> 8.5.0
2022-02-14T13:12:54.9154901Z npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.0>
2022-02-14T13:12:54.9155229Z npm notice Run `npm install -g npm@8.5.0` to update!
2022-02-14T13:12:54.9155453Z npm notice 
2022-02-14T13:12:56.0845847Z [0mRemoving intermediate container 4501f2b0efd3
2022-02-14T13:12:56.0846587Z  ---> 10587ac5b93f
2022-02-14T13:12:56.0847369Z Step 5/7 : RUN npm i -g renovate
2022-02-14T13:12:56.1086872Z  ---> Running in 526b3a944352
2022-02-14T13:13:06.7713953Z [91mnpm WARN EBADENGINE Unsupported engine {
2022-02-14T13:13:06.7714282Z npm WARN EBADENGINE   package: 'renovate@31.81.4',
2022-02-14T13:13:06.7714594Z npm WARN EBADENGINE   required: { node: '^14.15.0 || >=16.13.0', yarn: '^1.17.0' },
2022-02-14T13:13:06.7714946Z npm WARN EBADENGINE[0m[91m   current: { node: 'v15.14.0', npm: '7.10.0' }
2022-02-14T13:13:06.7715220Z npm WARN EBADENGINE }
2022-02-14T13:13:06.7715497Z [0m[91mnpm [0m[91mWARN EBADENGINE Unsupported engine {
2022-02-14T13:13:06.7715814Z npm WARN [0m[91mEBADENGINE   package: '@renovatebot/pep440@2.0.0',
2022-02-14T13:13:06.7716128Z npm [0m[91mWARN EBADENGINE   required: { node: '^14.15.0 || >=16.13.0', yarn: '^1.17.0' },
2022-02-14T13:13:06.7716454Z npm[0m[91m WARN[0m[91m EBADENGINE   current: { node: 'v15.14.0', npm: '7.10.0' }
2022-02-14T13:13:06.7716730Z npm WARN EBADENGINE[0m[91m }
2022-02-14T13:13:17.3956212Z [0m
2022-02-14T13:13:17.3956549Z added 553 packages, and audited 554 packages in 21s
2022-02-14T13:13:17.3956726Z 
2022-02-14T13:13:17.3956836Z 114 packages are looking for funding
2022-02-14T13:13:17.3957062Z   run `npm fund` for details
2022-02-14T13:13:17.3974864Z 
2022-02-14T13:13:17.3975331Z found 0 vulnerabilities
2022-02-14T13:13:17.3982278Z [91mnpm notice[0m[91m 
2022-02-14T13:13:17.3983217Z npm notice New major version of npm available! 7.10.0 -> 8.5.0
2022-02-14T13:13:17.3983660Z npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.0>
2022-02-14T13:13:17.3984262Z npm notice[0m[91m Run `npm install -g npm@8.5.0` to update!
2022-02-14T13:13:17.3984585Z npm notice 
2022-02-14T13:13:25.3218329Z [0mRemoving intermediate container 526b3a944352
2022-02-14T13:13:25.3219458Z  ---> 3e2e7978ce4d
2022-02-14T13:13:25.3219724Z Step 6/7 : COPY entrypoint.sh /entrypoint.sh
2022-02-14T13:13:26.5015283Z  ---> de3202719ee5
2022-02-14T13:13:26.5015656Z Step 7/7 : ENTRYPOINT ["/entrypoint.sh"]
2022-02-14T13:13:26.5236925Z  ---> Running in 37c6d97bbaf1
2022-02-14T13:13:27.6362453Z Removing intermediate container 37c6d97bbaf1
2022-02-14T13:13:27.6363134Z  ---> 0e3492f5634b
2022-02-14T13:13:27.6364778Z Successfully built 0e3492f5634b
2022-02-14T13:13:27.6392215Z Successfully tagged 7db2d7:5a66464a3dc148e184d99d9091fea3b7
2022-02-14T13:13:27.6415050Z ##[endgroup]
2022-02-14T13:13:27.6785262Z ##[group]Run actions/checkout@v2
2022-02-14T13:13:27.6785511Z with:
2022-02-14T13:13:27.6785739Z   repository: mprins/containers
2022-02-14T13:13:27.6786209Z   token: ***
2022-02-14T13:13:27.6786399Z   ssh-strict: true
2022-02-14T13:13:27.6786643Z   persist-credentials: true
2022-02-14T13:13:27.6786867Z   clean: true
2022-02-14T13:13:27.6787048Z   fetch-depth: 1
2022-02-14T13:13:27.6787250Z   lfs: false
2022-02-14T13:13:27.6787448Z   submodules: false
2022-02-14T13:13:27.6787637Z ##[endgroup]
2022-02-14T13:13:27.9193734Z Syncing repository: mprins/containers
2022-02-14T13:13:27.9195329Z ##[group]Getting Git version info
2022-02-14T13:13:27.9195846Z Working directory is '/home/runner/work/containers/containers'
2022-02-14T13:13:27.9196341Z [command]/usr/bin/git version
2022-02-14T13:13:27.9331053Z git version 2.35.1
2022-02-14T13:13:27.9332057Z ##[endgroup]
2022-02-14T13:13:27.9332434Z Deleting the contents of '/home/runner/work/containers/containers'
2022-02-14T13:13:27.9333484Z ##[group]Initializing the repository
2022-02-14T13:13:27.9333799Z [command]/usr/bin/git init /home/runner/work/containers/containers
2022-02-14T13:13:27.9386832Z hint: Using 'master' as the name for the initial branch. This default branch name
2022-02-14T13:13:27.9387224Z hint: is subject to change. To configure the initial branch name to use in all
2022-02-14T13:13:27.9387594Z hint: of your new repositories, which will suppress this warning, call:
2022-02-14T13:13:27.9387845Z hint: 
2022-02-14T13:13:27.9388169Z hint: 	git config --global init.defaultBranch <name>
2022-02-14T13:13:27.9388401Z hint: 
2022-02-14T13:13:27.9388748Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2022-02-14T13:13:27.9389191Z hint: 'development'. The just-created branch can be renamed via this command:
2022-02-14T13:13:27.9389442Z hint: 
2022-02-14T13:13:27.9389685Z hint: 	git branch -m <name>
2022-02-14T13:13:27.9394264Z Initialized empty Git repository in /home/runner/work/containers/containers/.git/
2022-02-14T13:13:27.9401683Z [command]/usr/bin/git remote add origin https://github.com/mprins/containers
2022-02-14T13:13:27.9441989Z ##[endgroup]
2022-02-14T13:13:27.9442677Z ##[group]Disabling automatic garbage collection
2022-02-14T13:13:27.9446718Z [command]/usr/bin/git config --local gc.auto 0
2022-02-14T13:13:27.9482368Z ##[endgroup]
2022-02-14T13:13:27.9501274Z ##[group]Setting up auth
2022-02-14T13:13:27.9502456Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2022-02-14T13:13:27.9528828Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2022-02-14T13:13:27.9870939Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2022-02-14T13:13:27.9900531Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2022-02-14T13:13:28.0169774Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2022-02-14T13:13:28.0214590Z ##[endgroup]
2022-02-14T13:13:28.0215431Z ##[group]Fetching the repository
2022-02-14T13:13:28.0223562Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +4ce4eca12df5d9abe21d4e21a885c0d1a4730f2d:refs/remotes/origin/master
2022-02-14T13:13:28.2751050Z remote: Enumerating objects: 15, done.        
2022-02-14T13:13:28.2757971Z remote: Counting objects:   6% (1/15)        
2022-02-14T13:13:28.2758865Z remote: Counting objects:  13% (2/15)        
2022-02-14T13:13:28.2759361Z remote: Counting objects:  20% (3/15)        
2022-02-14T13:13:28.2760095Z remote: Counting objects:  26% (4/15)        
2022-02-14T13:13:28.2760567Z remote: Counting objects:  33% (5/15)        
2022-02-14T13:13:28.2761615Z remote: Counting objects:  40% (6/15)        
2022-02-14T13:13:28.2762158Z remote: Counting objects:  46% (7/15)        
2022-02-14T13:13:28.2762859Z remote: Counting objects:  53% (8/15)        
2022-02-14T13:13:28.2763324Z remote: Counting objects:  60% (9/15)        
2022-02-14T13:13:28.2764016Z remote: Counting objects:  66% (10/15)        
2022-02-14T13:13:28.2764490Z remote: Counting objects:  73% (11/15)        
2022-02-14T13:13:28.2765275Z remote: Counting objects:  80% (12/15)        
2022-02-14T13:13:28.2765757Z remote: Counting objects:  86% (13/15)        
2022-02-14T13:13:28.2766453Z remote: Counting objects:  93% (14/15)        
2022-02-14T13:13:28.2766908Z remote: Counting objects: 100% (15/15)        
2022-02-14T13:13:28.2767627Z remote: Counting objects: 100% (15/15), done.        
2022-02-14T13:13:28.2768128Z remote: Compressing objects:   8% (1/12)        
2022-02-14T13:13:28.2768824Z remote: Compressing objects:  16% (2/12)        
2022-02-14T13:13:28.2769311Z remote: Compressing objects:  25% (3/12)        
2022-02-14T13:13:28.2770030Z remote: Compressing objects:  33% (4/12)        
2022-02-14T13:13:28.2770506Z remote: Compressing objects:  41% (5/12)        
2022-02-14T13:13:28.2771214Z remote: Compressing objects:  50% (6/12)        
2022-02-14T13:13:28.2771744Z remote: Compressing objects:  58% (7/12)        
2022-02-14T13:13:28.2772914Z remote: Compressing objects:  66% (8/12)        
2022-02-14T13:13:28.2773203Z remote: Compressing objects:  75% (9/12)        
2022-02-14T13:13:28.2773500Z remote: Compressing objects:  83% (10/12)        
2022-02-14T13:13:28.2773792Z remote: Compressing objects:  91% (11/12)        
2022-02-14T13:13:28.2774091Z remote: Compressing objects: 100% (12/12)        
2022-02-14T13:13:28.2774407Z remote: Compressing objects: 100% (12/12), done.        
2022-02-14T13:13:28.2777361Z remote: Total 15 (delta 0), reused 6 (delta 0), pack-reused 0        
2022-02-14T13:13:28.2866585Z From https://github.com/mprins/containers
2022-02-14T13:13:28.2870322Z  * [new ref]         4ce4eca12df5d9abe21d4e21a885c0d1a4730f2d -> origin/master
2022-02-14T13:13:28.2890349Z ##[endgroup]
2022-02-14T13:13:28.2891011Z ##[group]Determining the checkout info
2022-02-14T13:13:28.2892860Z ##[endgroup]
2022-02-14T13:13:28.2893431Z ##[group]Checking out the ref
2022-02-14T13:13:28.2897841Z [command]/usr/bin/git checkout --progress --force -B master refs/remotes/origin/master
2022-02-14T13:13:28.2952969Z Reset branch 'master'
2022-02-14T13:13:28.2953572Z branch 'master' set up to track 'origin/master'.
2022-02-14T13:13:28.2959133Z ##[endgroup]
2022-02-14T13:13:28.3002057Z [command]/usr/bin/git log -1 --format='%H'
2022-02-14T13:13:28.3032278Z '4ce4eca12df5d9abe21d4e21a885c0d1a4730f2d'
2022-02-14T13:13:28.3168952Z ##[group]Run tj-actions/renovate-config-validator@v1.2
2022-02-14T13:13:28.3169214Z with:
2022-02-14T13:13:28.3169423Z   config-file: renovate.json
2022-02-14T13:13:28.3169642Z ##[endgroup]
2022-02-14T13:13:28.3364287Z ##[command]/usr/bin/docker run --name db2d75a66464a3dc148e184d99d9091fea3b7_4b7525 --label 7db2d7 --workdir /github/workspace --rm -e INPUT_CONFIG-FILE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/containers/containers":"/github/workspace" 7db2d7:5a66464a3dc148e184d99d9091fea3b7
2022-02-14T13:13:29.1650263Z  WARN: RE2 not usable, falling back to RegExp
2022-02-14T13:13:29.1650542Z        "err": {
2022-02-14T13:13:29.1650745Z          "code": "MODULE_NOT_FOUND",
2022-02-14T13:13:29.1650977Z          "requireStack": [
2022-02-14T13:13:29.1651243Z            "/usr/local/lib/node_modules/renovate/dist/expose.cjs",
2022-02-14T13:13:29.1651581Z            "/usr/local/lib/node_modules/renovate/dist/util/regex.js",
2022-02-14T13:13:29.1651899Z            "/usr/local/lib/node_modules/renovate/dist/util/url.js",
2022-02-14T13:13:29.1652544Z            "/usr/local/lib/node_modules/renovate/dist/util/host-rules.js",
2022-02-14T13:13:29.1652899Z            "/usr/local/lib/node_modules/renovate/dist/datasource/docker/index.js",
2022-02-14T13:13:29.1653252Z            "/usr/local/lib/node_modules/renovate/dist/manager/ansible/index.js",
2022-02-14T13:13:29.1653571Z            "/usr/local/lib/node_modules/renovate/dist/manager/api.js",
2022-02-14T13:13:29.1653905Z            "/usr/local/lib/node_modules/renovate/dist/manager/index.js",
2022-02-14T13:13:29.1654246Z            "/usr/local/lib/node_modules/renovate/dist/config/options/index.js",
2022-02-14T13:13:29.1654570Z            "/usr/local/lib/node_modules/renovate/dist/config/massage.js",
2022-02-14T13:13:29.1655002Z            "/usr/local/lib/node_modules/renovate/dist/config-validator.js"
2022-02-14T13:13:29.1655263Z          ],
2022-02-14T13:13:29.1657009Z          "message": "Cannot find module 're2'\nRequire stack:\n- /usr/local/lib/node_modules/renovate/dist/expose.cjs\n- /usr/local/lib/node_modules/renovate/dist/util/regex.js\n- /usr/local/lib/node_modules/renovate/dist/util/url.js\n- /usr/local/lib/node_modules/renovate/dist/util/host-rules.js\n- /usr/local/lib/node_modules/renovate/dist/datasource/docker/index.js\n- /usr/local/lib/node_modules/renovate/dist/manager/ansible/index.js\n- /usr/local/lib/node_modules/renovate/dist/manager/api.js\n- /usr/local/lib/node_modules/renovate/dist/manager/index.js\n- /usr/local/lib/node_modules/renovate/dist/config/options/index.js\n- /usr/local/lib/node_modules/renovate/dist/config/massage.js\n- /usr/local/lib/node_modules/renovate/dist/config-validator.js",
2022-02-14T13:13:29.1662721Z          "stack": "Error: Cannot find module 're2'\nRequire stack:\n- /usr/local/lib/node_modules/renovate/dist/expose.cjs\n- /usr/local/lib/node_modules/renovate/dist/util/regex.js\n- /usr/local/lib/node_modules/renovate/dist/util/url.js\n- /usr/local/lib/node_modules/renovate/dist/util/host-rules.js\n- /usr/local/lib/node_modules/renovate/dist/datasource/docker/index.js\n- /usr/local/lib/node_modules/renovate/dist/manager/ansible/index.js\n- /usr/local/lib/node_modules/renovate/dist/manager/api.js\n- /usr/local/lib/node_modules/renovate/dist/manager/index.js\n- /usr/local/lib/node_modules/renovate/dist/config/options/index.js\n- /usr/local/lib/node_modules/renovate/dist/config/massage.js\n- /usr/local/lib/node_modules/renovate/dist/config-validator.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)\n    at Function.Module._load (node:internal/modules/cjs/loader:769:27)\n    at Module.require (node:internal/modules/cjs/loader:996:19)\n    at require (node:internal/modules/cjs/helpers:92:18)\n    at re2 (/usr/local/lib/node_modules/renovate/dist/expose.cjs:13:12)\n    at Object.<anonymous> (/usr/local/lib/node_modules/renovate/dist/util/regex.js:12:38)\n    at Module._compile (node:internal/modules/cjs/loader:1092:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)\n    at Module.load (node:internal/modules/cjs/loader:972:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:813:14)\n    at Module.require (node:internal/modules/cjs/loader:996:19)\n    at require (node:internal/modules/cjs/helpers:92:18)\n    at Object.<anonymous> (/usr/local/lib/node_modules/renovate/dist/util/url.js:10:17)\n    at Module._compile (node:internal/modules/cjs/loader:1092:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)\n    at Module.load (node:internal/modules/cjs/loader:972:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:813:14)\n    at Module.require (node:internal/modules/cjs/loader:996:19)\n    at require (node:internal/modules/cjs/helpers:92:18)\n    at Object.<anonymous> (/usr/local/lib/node_modules/renovate/dist/util/host-rules.js:10:15)"
2022-02-14T13:13:29.1665818Z        }
2022-02-14T13:13:30.4469634Z  INFO: Validating .github/renovate.json
2022-02-14T13:13:30.4533373Z FATAL: Unsupported file type
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mprins** [comment]
switched to `suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2` which is a drop in replacement that just works.

sse https://github.com/marketplace/actions/validate-renovate-configuration-with-renovate-config-validator

**Comment by jackton1** [comment]
@mprins Sorry for the delay getting to this had to deal with life stuff over the last few weeks this should be resolved now.
